# -*- coding: utf-8 -*-


from PyQt5 import QtCore, QtGui, QtWidgets
from mypyeqt.pvWidgets import pvQDoubleSpinBox, pvQLineEdit, pvQLabel, pvQMessageButton, pvQOZButton, pvQProgressBar
from hpm.widgets.PltWidget import PltWidget

from hpm.widgets.CustomWidgets import FlatButton, DoubleSpinBoxAlignRight, VerticalSpacerItem, NoRectDelegate, \
    HorizontalSpacerItem, ListTableWidget, VerticalLine, DoubleMultiplySpinBoxAlignRight


class Ui_xrda(object):
    def setupUi(self, xrda):
        #xrda.setObjectName("xrda")
        xrda.resize(1100, 615)
        self.centralwidget = QtWidgets.QWidget(xrda)
        self.centralwidget.setObjectName("centralwidget")
      
       

        xrda.setCentralWidget(self.centralwidget)
        
        self.menubar = QtWidgets.QMenuBar(xrda)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1236, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuControl = QtWidgets.QMenu(self.menubar)
        self.menuControl.setObjectName("menuControl")
        self.menuDisplay = QtWidgets.QMenu(self.menubar)
        self.menuDisplay.setObjectName("menuDisplay")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        xrda.setMenuBar(self.menubar)
        self.actionBackground = QtWidgets.QAction(xrda)
        self.actionBackground.setObjectName("actionBackground")
        self.actionSave_As = QtWidgets.QAction(xrda)
        self.actionSave_As.setEnabled(False)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionPrint = QtWidgets.QAction(xrda)
        self.actionPrint.setObjectName("actionPrint")
        self.actionPreferences = QtWidgets.QAction(xrda)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionExit = QtWidgets.QAction(xrda)
        self.actionExit.setObjectName("actionExit")
        self.actionPresets = QtWidgets.QAction(xrda)
        self.actionPresets.setObjectName("actionPresets")
        self.actionCalibrate_energy = QtWidgets.QAction(xrda)
        self.actionCalibrate_energy.setEnabled(False)
        self.actionCalibrate_energy.setObjectName("actionCalibrate_energy")
        self.actionPreferences_2 = QtWidgets.QAction(xrda)
        self.actionPreferences_2.setObjectName("actionPreferences_2")
        self.actionJCPDS = QtWidgets.QAction(xrda)
        self.actionJCPDS.setEnabled(False)
        self.actionJCPDS.setObjectName("actionJCPDS")
        self.actionFit_peaks = QtWidgets.QAction(xrda)
        self.actionFit_peaks.setObjectName("actionFit_peaks")
        self.actionAbout = QtWidgets.QAction(xrda)
        self.actionAbout.setObjectName("actionAbout")
        self.actionOpen_detector = QtWidgets.QAction(xrda)
        self.actionOpen_detector.setObjectName("actionOpen_detector")
        self.actionOpen_file = QtWidgets.QAction(xrda)
        self.actionOpen_file.setObjectName("actionOpen_file")
        self.actionCalibrate_2theta = QtWidgets.QAction(xrda)
        self.actionCalibrate_2theta.setEnabled(False)
        self.actionCalibrate_2theta.setObjectName("actionCalibrate_2theta")
        self.actionFluor = QtWidgets.QAction(xrda)
        self.actionFluor.setEnabled(False)
        self.actionFluor.setObjectName("actionFluor")
        self.actionROIs = QtWidgets.QAction(xrda)
        self.actionROIs.setEnabled(False)
        self.actionROIs.setObjectName("actionROIs")
        self.actionOverlay = QtWidgets.QAction(xrda)
        self.actionOverlay.setEnabled(False)
        self.actionOverlay.setObjectName("actionOverlay")
        self.actionExport_pattern = QtWidgets.QAction(xrda)
        self.actionExport_pattern.setEnabled(False)
        self.actionExport_pattern.setObjectName("actionExport_pattern")
        self.actionSave_next = QtWidgets.QAction(xrda)
        self.actionSave_next.setEnabled(False)
        self.actionSave_next.setObjectName("actionSave_next")
        self.actionPressure = QtWidgets.QAction(xrda)
        self.actionPressure.setEnabled(False)
        self.actionPressure.setObjectName("actionPressure")
        self.actionDisplayPrefs = QtWidgets.QAction(xrda)
        self.actionDisplayPrefs.setObjectName("actionDisplayPrefs")
        self.menuFile.addAction(self.actionOpen_file)
        self.menuFile.addAction(self.actionOpen_detector)
        self.menuFile.addAction(self.actionOverlay)
        self.menuFile.addAction(self.actionSave_next)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addAction(self.actionExport_pattern)
        self.menuFile.addAction(self.actionPreferences)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuControl.addAction(self.actionCalibrate_energy)
        self.menuControl.addAction(self.actionCalibrate_2theta)
        self.menuDisplay.addAction(self.actionJCPDS)
        self.menuDisplay.addAction(self.actionFluor)
        self.menuDisplay.addAction(self.actionROIs)
        self.menuDisplay.addAction(self.actionPressure)
        self.menuDisplay.addAction(self.actionDisplayPrefs)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuControl.menuAction())
        self.menubar.addAction(self.menuDisplay.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        QtCore.QMetaObject.connectSlotsByName(xrda)

        self.menuFile.setTitle("File")
        self.menuControl.setTitle("Control")
        self.menuDisplay.setTitle("Display")
        self.menuHelp.setTitle("Help")
        self.actionBackground.setText("Background")
        self.actionSave_As.setText("Save As")
        self.actionPrint.setText("Print")
        self.actionPreferences.setText("Preferences")
        self.actionExit.setText("Exit")
        self.actionPresets.setText("Presets...")
        self.actionCalibrate_energy.setText("Calibrate energy...")
        self.actionPreferences_2.setText("Preferences...")
        self.actionJCPDS.setText("Phase")
        self.actionFit_peaks.setText("Fit peaks...")
        self.actionAbout.setText("About")
        self.actionOpen_detector.setText("Open detector...")
        self.actionOpen_file.setText("Open file...")
        self.actionCalibrate_2theta.setText("Calibrate 2theta...")
        self.actionFluor.setText("Fluorescence")
        self.actionROIs.setText("ROIs")
        self.actionOverlay.setText("Overlay")
        self.actionExport_pattern.setText("Export pattern")
        self.actionSave_next.setText("Save next")
        self.actionPressure.setText("Pressure")
        self.actionDisplayPrefs.setText("Colors options")
